### ISSUE TITLE
`opacity` should come after `-ms-filter`

### ISSUE THREAD

**Issue by lencioni** [iamvdo/postcss-opacity#10]
Generally speaking, vendor-prefixed properties should always come before the standard property they are prefixing. This allows browsers that implement both the prefixed and the standard version to allow the standard version to override.

Although `-ms-filter` is not a vendor prefix of `opacity`, it still seems like it should appear before `opacity` after this transformation has occurred. CSS-Tricks backs this up as well: https://css-tricks.com/almanac/properties/o/opacity/

Would you be open to accepting a PR that changes the order?

**Comment by iamvdo** [comment]
fixed by #12
